# ---------------------------------------------------------
# Основные правила бота
# ---------------------------------------------------------
rules:
  - text: 'Привет'                                                        # Человекопонятный текст правила, используется для логов и метрик
    pattern: '(?i)([пpg]\s*[рrh]\s*[иi1lb]\s*[вvd]\s*[еe3ft]\s*[тt7yn])'  # Регулярное выражение для поиска совпадений в сообщениях.
                                                                          # Здесь учитываются кириллица и похожие латинские буквы, пробелы, цифры.
                                                                          # (?i) – флаг "без учета регистра".
    response: 'Здрасьте'                                                  # Ответ бота, который будет отправлен при совпадении правила

# ---------------------------------------------------------
# Настройки логирования
# ---------------------------------------------------------
log_settings:
  directory: "logs"                                                       # Директория для хранения логов
  filename: "app.log"                                                     # Имя файла лога
  max_size: 100                                                           # Максимальный размер одного лог-файла в MB
  max_backups: 10                                                         # Количество старых файлов для ротации
  max_age: 7                                                              # Срок хранения файлов в днях
  compress: true                                                          # Сжимать старые файлы gzip
  level: "info"                                                           # Уровень логирования: debug, info, warn, error
  console_enabled: true                                                   # Вывод логов на консоль (true/false)

# ---------------------------------------------------------
# Режим работы бота
# ---------------------------------------------------------
bot_mode: "first_last"                                                    # Режим обработки сообщений:
                                                                          # "first_last" – проверка только первого и последнего слова
                                                                          # "all" – проверка всех слов сообщения

# ---------------------------------------------------------
# Секреты и токены
# ---------------------------------------------------------
secrets: config/secrets.yaml                                              # Путь к файлу с секретами:
                                                                          # Telegram token и другие конфиденциальные данные

# ---------------------------------------------------------
# Сервис
# ---------------------------------------------------------
service_port: 9090                                                        # Порт, на котором будет запущен HTTP-сервер для метрик Prometheus
